### ISSUE TITLE
when patch apsd has a error

### ISSUE THREAD

**Issue by FluxPeak** [meeee/pushproxy#24]
Thanks for the great project!
I'm trying to make it work on 10.8.4,  when patch apsd ,i got this:

```
$ setup/osx/patch_apsd.py apsd ca.der server.der louis
Traceback (most recent call last):
  File "setup/osx/patch_apsd.py", line 93, in <module>
    main()
  File "setup/osx/patch_apsd.py", line 34, in main
    patch(apsd_path, dict(replacements), output_path)
  File "setup/osx/patch_apsd.py", line 79, in patch
    " or it occurs multiple times: %s" % repr(needle))
ValueError: Source binary doesn't contain replacement key  or it occurs multiple times: '\xb9`\x04\x00\x00'
```

and I have copy /System/Library/PrivateFrameworks/ApplePushService.framework/apsd  to push proxy-master/apsd.

**Comment by mfrister** [comment]
Have you tried skipping the patching? IIRC [certificate pinning started with OS X 10.9](https://github.com/meeee/pushproxy#ios--7-os-x--109), so you might not need it.

This would also explain why the script can't find the certificate in the binary.

**Comment by FluxPeak** [comment]
Thanks.
I try again, and got this:

```
$ sudo ./runpush.sh
2015-04-14 11:31:20+0800 Log opened.
2015-04-14 11:31:20+0800 twistd 12.2.0 (/usr/bin/python 2.7.5) starting up.
2015-04-14 11:31:20+0800 reactor class: twisted.internet.selectreactor.SelectReactor.
2015-04-14 11:31:20+0800 Traceback (most recent call last):
2015-04-14 11:31:20+0800   File "/usr/bin/twistd", line 14, in <module>
2015-04-14 11:31:20+0800     run()
2015-04-14 11:31:20+0800   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/scripts/twistd.py", line 27, in run
2015-04-14 11:31:20+0800     app.run(runApp, ServerOptions)
2015-04-14 11:31:20+0800   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/application/app.py", line 652, in run
2015-04-14 11:31:20+0800     runApp(config)
2015-04-14 11:31:20+0800   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/scripts/twistd.py", line 23, in runApp
2015-04-14 11:31:20+0800     _SomeApplicationRunner(config).run()
2015-04-14 11:31:20+0800   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/application/app.py", line 390, in run
2015-04-14 11:31:20+0800     self.postApplication()
2015-04-14 11:31:20+0800   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/scripts/_twistd_unix.py", line 230, in postApplication
2015-04-14 11:31:20+0800     self.startApplication(self.application)
2015-04-14 11:31:20+0800   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/scripts/_twistd_unix.py", line 340, in startApplication
2015-04-14 11:31:20+0800     service.IService(application).privilegedStartService()
2015-04-14 11:31:20+0800   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/application/service.py", line 277, in privilegedStartService
2015-04-14 11:31:20+0800     service.privilegedStartService()
2015-04-14 11:31:20+0800   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/application/internet.py", line 105, in privilegedStartService
2015-04-14 11:31:20+0800     self._port = self._getPort()
2015-04-14 11:31:20+0800   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/application/internet.py", line 133, in _getPort
2015-04-14 11:31:20+0800     'listen%s' % (self.method,))(*self.args, **self.kwargs)
2015-04-14 11:31:20+0800   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/posixbase.py", line 508, in listenSSL
2015-04-14 11:31:20+0800     tlsFactory = tls.TLSMemoryBIOFactory(contextFactory, False, factory)
2015-04-14 11:31:20+0800   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/protocols/tls.py", line 598, in __init__
2015-04-14 11:31:20+0800     contextFactory.getContext()
2015-04-14 11:31:20+0800   File "/work/IMessage/pushproxy-master/src/icl0ud/push/intercept.py", line 268, in getContext
2015-04-14 11:31:20+0800     ctx.set_session_cache_mode(SSL.SESS_CACHE_OFF)
2015-04-14 11:31:20+0800 AttributeError: 'OpenSSL.SSL.Context' object has no attribute 'set_session_cache_mode'
```

so remove "pushproxy-master/src/icl0ud/push/intercept.py" line 268,  then it work.
but send message to a new person, i got this:

```
2015-04-14 11:36:39+0800 [#0] New connection from 127.0.0.1:49231
2015-04-14 11:36:39+0800 [#0] SSL handshake done: Device: 1B5790EB-CEAA-4109-9D1A-D1B9337DDBA0
2015-04-14 11:36:39+0800 [#0] Connecting to push server: 17.172.232.135:5223
2015-04-14 11:36:39+0800 Starting factory <icl0ud.push.intercept.InterceptClientFactory instance at 0x10a9c3f80>
2015-04-14 11:36:40+0800 [#0] -> APSConnect presenceFlags: 00000005 state: 01
                                   push token: 2154f2fc3fde28c827c1d84563ddeff471c8f32fdbb3a53448566131f2147cdc
2015-04-14 11:37:09+0800 [#1] New connection from 127.0.0.1:49234
2015-04-14 11:37:09+0800 Unable to connect to peer: [Failure instance: Traceback: <class 'OpenSSL.SSL.Error'>: [('SSL routines', 'SSL_GET_PREV_SESSION', 'session id context uninitialized')]
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/selectreactor.py:150:_doReadOrWrite
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/tcp.py:203:doRead
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/tcp.py:209:_dataReceived
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/protocols/tls.py:417:dataReceived
--- <exception caught here> ---
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/protocols/tls.py:356:_flushReceiveBIO
]
2015-04-14 11:37:25+0800 [#2] New connection from 127.0.0.1:49238
2015-04-14 11:37:25+0800 [#2] SSL handshake done: Device: 1B5790EB-CEAA-4109-9D1A-D1B9337DDBA0
2015-04-14 11:37:25+0800 [#2] Connecting to push server: 17.172.232.59:5223
2015-04-14 11:37:25+0800 Starting factory <icl0ud.push.intercept.InterceptClientFactory instance at 0x10a9c9950>
2015-04-14 11:37:28+0800 [#2] -> APSConnect presenceFlags: 00000005 state: 01
                                   push token: 2154f2fc3fde28c827c1d84563ddeff471c8f32fdbb3a53448566131f2147cdc
2015-04-14 11:37:55+0800 [#3] New connection from 127.0.0.1:49241
2015-04-14 11:37:55+0800 Unable to connect to peer: [Failure instance: Traceback: <class 'OpenSSL.SSL.Error'>: [('SSL routines', 'SSL_GET_PREV_SESSION', 'session id context uninitialized')]
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/selectreactor.py:150:_doReadOrWrite
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/tcp.py:203:doRead
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/tcp.py:209:_dataReceived
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/protocols/tls.py:417:dataReceived
--- <exception caught here> ---
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/protocols/tls.py:356:_flushReceiveBIO
]
2015-04-14 11:38:11+0800 [#4] New connection from 127.0.0.1:49245
2015-04-14 11:38:11+0800 [#4] SSL handshake done: Device: 1B5790EB-CEAA-4109-9D1A-D1B9337DDBA0
2015-04-14 11:38:11+0800 [#4] Connecting to push server: 17.172.232.59:5223
2015-04-14 11:38:11+0800 Starting factory <icl0ud.push.intercept.InterceptClientFactory instance at 0x10a9c9f80>
2015-04-14 11:38:15+0800 [#4] -> APSConnect presenceFlags: 00000005 state: 01
                                   push token: 2154f2fc3fde28c827c1d84563ddeff471c8f32fdbb3a53448566131f2147cdc
2015-04-14 11:38:41+0800 [#5] New connection from 127.0.0.1:49248
2015-04-14 11:38:41+0800 Unable to connect to peer: [Failure instance: Traceback: <class 'OpenSSL.SSL.Error'>: [('SSL routines', 'SSL_GET_PREV_SESSION', 'session id context uninitialized')]
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/selectreactor.py:150:_doReadOrWrite
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/tcp.py:203:doRead
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/tcp.py:209:_dataReceived
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/protocols/tls.py:417:dataReceived
--- <exception caught here> ---
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/protocols/tls.py:356:_flushReceiveBIO
]
2015-04-14 11:40:11+0800 [#6] New connection from 127.0.0.1:49252
2015-04-14 11:40:11+0800 [#6] SSL handshake done: Device: 1B5790EB-CEAA-4109-9D1A-D1B9337DDBA0
2015-04-14 11:40:11+0800 [#6] Connecting to push server: 17.172.232.135:5223
2015-04-14 11:40:11+0800 Starting factory <icl0ud.push.intercept.InterceptClientFactory instance at 0x10a9cb5a8>
2015-04-14 11:40:12+0800 [#6] -> APSConnect presenceFlags: 00000005 state: 01
                                   push token: 2154f2fc3fde28c827c1d84563ddeff471c8f32fdbb3a53448566131f2147cdc
```

I find the reason 
![](https://cloud.githubusercontent.com/assets/11918441/7130058/3556b1ee-e29c-11e4-8f65-8668690e98ca.png)
how to fix it?

**Comment by mfrister** [comment]
Commenting out the line is causing the error. As described in the comment, you'll need pyOpenSSL >= 0.14.

**Comment by FluxPeak** [comment]
```
2015-04-20 18:07:12+0800   File "/work/IMessage/pushproxy-master/src/icl0ud/push/intercept.py", line 268, in getContext
2015-04-20 18:07:12+0800     ctx.set_session_cache_mode(SSL.SESS_CACHE_OFF)
2015-04-20 18:07:12+0800 AttributeError: 'OpenSSL.SSL.Context' object has no attribute 'set_session_cache_mode'
bogon:src louis$ pip show pyopenssl
---
Metadata-Version: 1.1
Name: pyOpenSSL
Version: 0.14
Summary: Python wrapper module around the OpenSSL library
Home-page: https://github.com/pyca/pyopenssl
Author: Jean-Paul Calderone
Author-email: exarkun@twistedmatrix.com
License: APL2
Location: /Library/Python/2.7/site-packages
Requires: cryptography, six
```

it's 0.14

**Comment by FluxPeak** [comment]
when run python used 0.13, i have fix this. TKS.

**Comment by mfrister** [comment]
So you commented out the `set_session_cache_mode` line and used pyOpenSSL 0.13?

As this error doesn't always appear, it might be a coincidence that it works now.

Are you sure pyOpenSSL 0.14 is the version that was actually used? According to their [changelog](https://github.com/pyca/pyopenssl/blob/master/ChangeLog#L153-L160), they added the method in 0.14.

Could you add the following lines `log.msg(SSL.__file__)` just before the `set_session_cache_mode` line? That should tell you which version of pyOpenSSL you're using and where the source files are.

``` python
import OpenSSL
log.msg('pyOpenSSL %s' % OpenSSL.__version__)
log.msg('source: %s' % OpenSSL.__file__)
```
