### ISSUE TITLE
connect to apple push server error "key values mismatch"

### ISSUE THREAD

**Issue by FluxPeak** [meeee/pushproxy#25]
```
2015-04-23 09:41:29+0800 Starting factory <twisted.spread.pb.PBServerFactory instance at 0x10fb80998>
2015-04-23 09:41:36+0800 [#0] New connection from 127.0.0.1:49168
2015-04-23 09:41:36+0800 [#0] SSL handshake done: Device: A37E8C14-9C23-4DD1-8D70-A768D5F53BB6
2015-04-23 09:41:36+0800 [#0] Connecting to push server: 17.172.232.218:5223
2015-04-23 09:41:36+0800 '[#0] SSLInfoCallback Exception:'
2015-04-23 09:41:36+0800 'Traceback (most recent call last):\n  File "/work/PyCharm/pushproxy-master/src/icl0ud/push/intercept.py", line 139, in SSLInfoCallback\n    self.connectToServer()\n  File "/work/PyCharm/pushproxy-master/src/icl0ud/push/intercept.py", line 168, in connectToServer\n    self.getClientContextFactory())\n  File "/Library/Python/2.7/site-packages/twisted/internet/posixbase.py", line 452, in connectSSL\n    tlsFactory = tls.TLSMemoryBIOFactory(contextFactory, True, factory)\n  File "/Library/Python/2.7/site-packages/twisted/protocols/tls.py", line 594, in __init__\n    contextFactory.getContext()\n  File "/work/PyCharm/pushproxy-master/src/icl0ud/push/intercept.py", line 105, in getContext\n    ctx.use_privatekey_file(self.cert)\n  File "/Library/Python/2.7/site-packages/OpenSSL/SSL.py", line 458, in use_privatekey_file\n    self._raise_passphrase_exception()\n  File "/Library/Python/2.7/site-packages/OpenSSL/SSL.py", line 429, in _raise_passphrase_exception\n    _raise_current_error()\n  File "/Library/Python/2.7/site-packages/OpenSSL/_util.py", line 22, in exception_from_error_queue\n    raise exceptionType(errors)\nError: [(\'x509 certificate routines\', \'X509_check_private_key\', \'key values mismatch\')]\n'
```

**Comment by mfrister** [comment]
Here's the traceback in a readable form (I also took the liberty to add a missing newline after ``` in your description):

```
Traceback (most recent call last):
  File "/work/PyCharm/pushproxy-master/src/icl0ud/push/intercept.py", line 139, in SSLInfoCallback
    self.connectToServer()
  File "/work/PyCharm/pushproxy-master/src/icl0ud/push/intercept.py", line 168, in connectToServer
    self.getClientContextFactory())
  File "/Library/Python/2.7/site-packages/twisted/internet/posixbase.py", line 452, in connectSSL
    tlsFactory = tls.TLSMemoryBIOFactory(contextFactory, True, factory)
  File "/Library/Python/2.7/site-packages/twisted/protocols/tls.py", line 594, in __init__
    contextFactory.getContext()
  File "/work/PyCharm/pushproxy-master/src/icl0ud/push/intercept.py", line 105, in getContext
    ctx.use_privatekey_file(self.cert)
  File "/Library/Python/2.7/site-packages/OpenSSL/SSL.py", line 458, in use_privatekey_file
    self._raise_passphrase_exception()
  File "/Library/Python/2.7/site-packages/OpenSSL/SSL.py", line 429, in _raise_passphrase_exception
    _raise_current_error()
  File "/Library/Python/2.7/site-packages/OpenSSL/_util.py", line 22, in exception_from_error_queue
    raise exceptionType(errors)
Error: [('x509 certificate routines', 'X509_check_private_key', 'key values mismatch')]
```

So the actual error returned by OpenSSL is:

```
'X509_check_private_key', 'key values mismatch'
```

If you [google that](https://encrypted.google.com/search?hl=en&q=%27X509_check_private_key%27%2C%20%27key%20values%20mismatch%27), you'll find out pretty fast that your certificate and private key don't match.

**Comment by FluxPeak** [comment]
I do the same step on mac 10.10,then it work. mac 10.9 show this error.

**Comment by mfrister** [comment]
So either you made a mistake or OpenSSL on 10.9 has a bug.

Do the certificate/private key generated on 10.10 work on 10.9?

**Comment by FluxPeak** [comment]
I found this:

```
-----BEGIN RSA PRIVATE KEY-----
data
-----END RSA PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
data
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
data
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
data
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
data
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
data
-----END CERTIFICATE-----
```

in the uuid.pem have many CERTIFICATE.
I reinstall osx, it okey now.
